export const demoContent = `Introduction to Data Structures: Arrays, Linked Lists, and Big-O

Welcome to the first lecture in our data structures series. Today we will cover three fundamental topics: what data structures are, the array and linked list data structures, and how we analyze algorithm efficiency using Big-O notation. By the end of this lecture, you will understand the trade-offs between different data structures and be able to reason about which one to use in a given situation.

What is a Data Structure?

A data structure is a specialized format for organizing, processing, retrieving, and storing data. Different data structures excel at different tasks, and there is no single best data structure for all situations. Choosing the right data structure can make the difference between a program that runs in milliseconds and one that takes hours to complete. Every data structure has three key operations: insertion, deletion, and access. The efficiency of these operations varies dramatically depending on the structure you choose. Understanding these trade-offs is a core skill in computer science and software engineering. When designing a system, you must consider not only the types of operations you will perform most frequently but also the size of the data you are working with.

Arrays

An array is the simplest and most widely used data structure. It stores elements in contiguous memory locations, meaning each element sits right next to its neighbor in memory with no gaps. This compact layout makes arrays incredibly fast for random access: retrieving the element at any given index takes the same amount of time regardless of the array's size. In Big-O notation, we say array access is O(1), or constant time. This is because the memory address of any element can be calculated directly using the formula: base_address + (index * element_size). However, inserting or deleting an element in the middle of an array is expensive. Every element after the insertion or deletion point must shift over by one position to maintain contiguity. In the worst case, you might shift every element, making these operations O(n), where n is the number of elements in the array. Arrays also have a fixed size determined at allocation time. If you allocate an array of 100 integers and later need to store 150, you must create a new, larger array and copy every element over, which is another O(n) operation.

Linked Lists

A linked list solves the sizing problem of arrays by using a completely different approach to memory layout. Instead of storing elements contiguously, each element, called a node, contains the data plus a pointer to the next node in the sequence. The nodes can be scattered anywhere in memory; the pointers keep the list connected. This means the list grows and shrinks dynamically with no copying overhead. Inserting or deleting a node at the beginning of a linked list is O(1) — you simply update the head pointer to point to the new first node. This is dramatically faster than an array, where inserting at the front requires shifting every existing element. The trade-off is access time. To find the fifth element, you must start at the first node and follow four pointers sequentially, making access O(n) in the worst case. Linked lists also use more memory than arrays because each node must store both data and a pointer. The two most common variants are singly linked lists, where each node points only to the next node in one direction, and doubly linked lists, where each node points both forward to the next node and backward to the previous node, allowing traversal in either direction. Doubly linked lists use even more memory but make deletion from the middle more efficient.

Big-O Notation

Big-O notation is the language we use to describe the efficiency of algorithms. It describes the upper bound of an algorithm's growth rate as the input size increases toward infinity. Big-O ignores constant factors and focuses on the dominant term that determines growth. For example, if an operation takes 5n + 3 steps, we simplify it to O(n). If it takes n-squared plus 100n steps, we simplify it to O(n-squared) because the n-squared term dominates for large values of n. The common complexity classes, ordered from fastest to slowest, are: O(1) constant time — the operation takes the same amount of time regardless of input size, like accessing an array element by index; O(log n) logarithmic time — the operation grows slowly as input increases, like binary search on a sorted array; O(n) linear time — time grows proportionally to the input size, like iterating through an array; O(n log n) linearithmic time — common in efficient sorting algorithms like merge sort; O(n-squared) quadratic time — time grows with the square of the input, like nested loops iterating over all pairs; and O(2 to the n) exponential time — time doubles with each additional input element, quickly becoming impractical. Understanding Big-O notation gives you the vocabulary to compare algorithms and data structures mathematically, enabling you to make informed design decisions before writing a single line of code.

Practical Comparison

When should you use an array versus a linked list? Arrays are the better choice when you frequently need to access elements by index, when you know the maximum size in advance, or when memory overhead is a concern. They also have better cache locality because their elements are stored contiguously, which modern CPUs exploit through prefetching. Linked lists excel when you frequently insert or delete elements at the beginning or end, when you do not know the size in advance, or when you never need random access. Real-world applications of linked lists include implementing undo functionality in editors, representing adjacency lists in graphs, and managing free memory blocks in operating systems.

Summary

Arrays offer fast O(1) access but slow O(n) insertions and deletions. Linked lists offer fast O(1) insertions and deletions at the ends but slow O(n) access. Choosing between them depends on whether you need to access elements by position frequently or modify the collection frequently. Big-O notation gives you the vocabulary to compare these trade-offs mathematically. In the next lecture, we will explore stacks and queues, two higher-level abstract data types that can be built on top of both arrays and linked lists.`
